# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='邮箱验证码')),
                ('send_type', models.CharField(choices=[('forget', '找回密码'), ('register', '注册')], max_length=20)),
                ('send_time', models.DateTimeField(auto_now=True, verbose_name='发送验证时间')),
                ('email', models.EmailField(default='', max_length=30, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'db_table': 'email_verify_record',
            },
        ),
        migrations.CreateModel(
            name='Scrollbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('roll_image', models.ImageField(max_length=200, upload_to='roll_image/', verbose_name='滚动图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '滚动图',
                'db_table': 'scroll_bar',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=20, verbose_name='昵称')),
                ('birthday', models.DateField(default='', max_length=30, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10)),
                ('address', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('head_image', models.ImageField(null=True, upload_to='head_image/')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='登入时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'users_userprofile',
            },
        ),
    ]
