# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='城市名')),
                ('describe', models.TextField(verbose_name='城市描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='OrganInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('describe', models.TextField(verbose_name='机构描述')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('store_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('org_log', models.ImageField(null=True, upload_to='org_log/', verbose_name='机构log')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '课程信息',
                'db_table': 'organ_info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='教师名称')),
                ('work_year', models.IntegerField(verbose_name='工作年限')),
                ('work_company', models.CharField(max_length=30, verbose_name='工作公司')),
                ('post', models.CharField(max_length=30, verbose_name='职务')),
                ('charact', models.CharField(max_length=30, verbose_name='教学特点')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('store_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganInfo', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师',
                'db_table': 'teacher',
            },
        ),
    ]
